### ISSUE TITLE
in the list view group articles by feed

### ISSUE THREAD

**Issue by Zayatoshi** [Tunous/SwipeNews-Issues#100]
I wanted to encourage you to develop your SwipeNews application. Indeed I enrolled in the Beta program, I discovered your app and it really fantastic.
Fluidity, ergonomics, simplicity, comfort of reading, it is one of the best of the Playstore for me, coupled with Inoreader.
Just two small suggestions to put in your to do list:
 
1 / The possibility in the list view, to classify the articles by grouping them by feed. Currently there is only the possibility of classifying them from the most recent to the oldest or vice versa. This would really be a great step forward, there is almost no application offering this option in the playstore.

2 / Still in the list view the possibility of having a short summary of the article below its title and its possible photo.

**Comment by Tunous** [comment]
Thanks. I've already replied to your email and created #99.

Displaying summary in article list is already possible from Settings > Appearance > Articles look.
