### ISSUE TITLE
Only show unread articles doesn't work for streams/groups

### ISSUE THREAD

**Issue by kontrastylez** [Tunous/SwipeNews-Issues#105]
Since the last update, all (read and unread) articles are shown, when a stream/group is opened via navigation drawer. The option "only unread" is always deselected in these screens.

**Comment by Tunous** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Only show unread articles doesn't work for streams/groups](https://trello.com/c/P3TkejCD/1100-only-show-unread-articles-doesnt-work-for-streams-groups)

**Comment by Tunous** [comment]
Got it. I have accidentally negated a condition check when refactoring code to work with Feedbin. So instead of targeting tags as requested in #52 it targeted folders instead.
