### ISSUE TITLE
New articles show after swiping though the initial 20 old ones

### ISSUE THREAD

**Issue by chtk** [Tunous/SwipeNews-Issues#109]
I read articles from old to new. 

After having swiped through 20 articles from the top of my stack, the next 20 are picked from the bottom in new to old order.

**Comment by Tunous** [comment]
I also read articles from oldest to newest but never experienced this issue. But I'll try to reproduce it somehow.

**Comment by chtk** [comment]
I really should have started out with this. But I cleared app data and reconnected my Inoreader account. After swiping through 20 old articles from the reading list new ones still show up.

**Comment by Tunous** [comment]
With new offline mode the way how articles are loaded has been reimplemented and this issue should no longer happen. 

This is done in upcoming 0.22.0 version.
