### ISSUE TITLE
Sometimes articles aren't shown correctly

### ISSUE THREAD

**Issue by kontrastylez** [Tunous/SwipeNews-Issues#129]
I have created a screen record for demonstration. The second app is Inoreader.

[Link to Google Drive](https://drive.google.com/file/d/16hS_CYVIP4p22oGAUmTJ2zoOV5bbEnK3/view?usp=drivesdk)

**Comment by Tunous** [comment]
Cause: code to mark articles older than specific time incorrectly marks also articles posted **exactly** at that time.
