### ISSUE TITLE
Unread counter in toolbar

### ISSUE THREAD

**Issue by kontrastylez** [Tunous/SwipeNews-Issues#35]

**Comment by Tunous** [comment]
What's this exactly about?

Unread counter already should be displayed next to each tag/folder and main reading list in the navigation drawer. If this doesn't work then I guess there must be a bug somewhere.

**Comment by kontrastylez** [comment]
Yes, there is a counter for reading list in navigation drawer. But I'm not sure, if it always refreshes correctly. Sometimes i have to reopen the app to show the correct count, after i refreshed my articles.

But what i meant with this issue, is a counter in article list. For example, many Twitter clients have this and for me, this is more useful. Here is an example screenshot:

![screenshot_2016-11-06-18-16-13](https://cloud.githubusercontent.com/assets/23293407/20039960/42e553ea-a44e-11e6-9cab-11bfb578ced4.png)

**Comment by Tunous** [comment]
I see. I can implement that unread counter too. Looks pretty nice.

Let's split this issue into 2. This one will be for counter in toolbar and #38 will be for bug with refreshing.

**Comment by Tunous** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Unread counter in toolbar](https://trello.com/c/HAgPAA9s/847-unread-counter-in-toolbar)

**Comment by Tunous** [comment]
Additional idea: make it also available inside of article content screen.
