### ISSUE TITLE
Viewing tags without unread articles in navigation drawer

### ISSUE THREAD

**Issue by kontrastylez** [Tunous/SwipeNews-Issues#36]
In inoreader, you can see the tagged articles in navigation drawer. Would be nice to have this in SwipeNews.
![screenshot_2016-11-06-14-23-20](https://cloud.githubusercontent.com/assets/23293407/20038063/12183118-a42d-11e6-88fc-52fb186aee88.png)

**Comment by Tunous** [comment]
The current implementation of navigation drawer displays only the items which have unread articles. To see a list of all tags you have to go to the *Edit Subscriptions* screen.

I have thought about this for some time already and I have few ideas that could improve it:

1. Option to always display all items in the navigation drawer, even if they don't have unread articles.
2. Option to always display all tags. Folders and subscription would appear as currently - only when they have unread articles.
3. A feature allowing to manually select which tags/folders would be always displayed. 

Now, I think that I'll add both 1 and 2 as options disabled by default but I'm unsure about 3. Is it something that would be useful?

Let me know what do you think about this or if you have other ideas.

**Comment by kontrastylez** [comment]
For me, option 2 would be the best. Option 1 could also be useful for others. Option 3 is definitely nothing that i would use, but it don't know, if it could be useful for others.

**Comment by Tunous** [comment]
Another thing. I can see that in the image Inoreader groups tags under expandable entry. Currently SwipeNews displays them inline like folders. Should it be changed so tags appear under expandable entry here too? Or perhaps add that as an option for users to decide.

**Comment by kontrastylez** [comment]
I think it would be better to have an expandable folder "Tags" under which all tags are listed, like in inoreader app.

**Comment by Tunous** [comment]
# Options to add 

- [ ] Always display all items in drawer (disabled by default)
- [ ] Always display tags in drawer (enabled by default)
- [ ] Group tags (enabled by default)

**Comment by Tunous** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Viewing tags without unread articles in navigation drawer](https://trello.com/c/eWnABiUa/841-viewing-tags-without-unread-articles-in-navigation-drawer)
