### ISSUE TITLE
Reading list unread counter doesn't always refresh correctly

### ISSUE THREAD

**Issue by Tunous** [Tunous/SwipeNews-Issues#38]

**Comment by Tunous** [comment]
@kontrastylez Can you inspect this issue and tell me if it happens even if you don't enter article content screen?

From my observations there might be an issue with it not always updating when returning from that screen but I'm not 100% sure about that.

**Comment by kontrastylez** [comment]
It happens, when I open article content and also if I don't open article content.

I'm not sure, if it only happens, after a refresh, when before everything was read.

**Comment by kontrastylez** [comment]
After a little bit of testing, it seems like it only happens after a refresh, when before everything was read. When there is already an unread counter shown for reading list, it seems to update correctly.

**Comment by Tunous** [comment]
Thank you! That makes it much easier to find what's wrong. I'll try to fix it for next version.

**Comment by Tunous** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Unread counter for reading list doesn't update after refresh](https://trello.com/c/pMRB4mir/825-unread-counter-for-reading-list-doesn-t-update-after-refresh)
