### ISSUE TITLE
TeslaUnread support

### ISSUE THREAD

**Issue by kontrastylez** [Tunous/SwipeNews-Issues#42]
Would be nice, if TeslaUnread could be supported to show the counter for unread articles in nova launcher.

http://novalauncher.com/teslaunread-api/

**Comment by Tunous** [comment]
This will most likely require background syncing to have updated information without starting application. That means that it won't be possible before implementing #12.

**Comment by Tunous** [comment]
I tested how this integration works with other applications and it is really useful. I like how I don't have to open them just to see if there is content anymore. That makes me want to implement this much earlier. Perhaps I could manage to add much simpler background syncing of only unread counts before offline mode.

I think I should have it ready by v0.18.0 or a bit later. Let's mark it like this for now.

**Comment by Tunous** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [TeslaUnread support](https://trello.com/c/umhiHlcq/879-teslaunread-support)
