### ISSUE TITLE
Always show read articles in tag screens

### ISSUE THREAD

**Issue by kontrastylez** [Tunous/SwipeNews-Issues#52]
Normally i have already read tagged articles. An option to always show all articles in a tag screen would be great. This should not affect the setting for reading list.

**Comment by Tunous** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Always show read articles in tag screens](https://trello.com/c/XX4HZRXn/860-always-show-read-articles-in-tag-screens)
