### ISSUE TITLE
Mark as read, if article is opened in browser from article list

### ISSUE THREAD

**Issue by kontrastylez** [Tunous/SwipeNews-Issues#54]
When I open an article in browser directly from article list (for example via swipe action), it would be nice, if the article would be marked as read.

**Comment by Tunous** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Mark as read when opening article in browser](https://trello.com/c/UxgBCnVp/886-mark-as-read-when-opening-article-in-browser)
