### ISSUE TITLE
Speed up animations for swipe actions in article list

### ISSUE THREAD

**Issue by kontrastylez** [Tunous/SwipeNews-Issues#55]
Would it be possible, to have a setting to set the duration (possible options: fast and slow) for swipe actions in article list? I often star articles via swipe gesture to read them later. It would be nice, if the animation (starring of article) would be finished faster.

**Comment by Tunous** [comment]
Yes it is possible to add that option but I think that would be a bad idea. It's better to have that speed adjusted to be good for most people without the need for changes. 

Which part of the animation is bad for you? The part where it doesn't move or the part where it returns to original position? Perhaps I could adjust it a bit. 

Also what is the problem with the current speed? It shouldn't have bad impact on the usage of the app. You are still able to swipe and scroll to other articles while the animation plays. Even better - you can swipe multiple articles at the same time. 

Myself I save many articles to Pocket in a row and the animation doesn't slow me down at all.

**Comment by kontrastylez** [comment]
Sorry, I never tried to swipe the next item, before animation was finished. :-D

Thanks for the tip. So, everything is fine for me with animation speed as it is now. Animations look definately better than if they would be finished faster.

**Comment by Tunous** [comment]
Ok, that's great :)
