### ISSUE TITLE
Mark as read when opening article in browser doesn't refresh counter

### ISSUE THREAD

**Issue by kontrastylez** [Tunous/SwipeNews-Issues#57]
When an article is opened directly in browser, it is marked as read, but it doesn't refresh the counters in toolbar and navigation bar. After a refresh of article list, the counters are correct.

**Comment by Tunous** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Mark as read when opening article in browser doesn't refresh counter](https://trello.com/c/yLLWXEER/891-mark-as-read-when-opening-article-in-browser-doesn-t-refresh-counter)
