### ISSUE TITLE
Load next group after Mark all as read

### ISSUE THREAD

**Issue by fi9o** [Tunous/SwipeNews-Issues#60]
Hi, is there any way to add this option? 
Its working in gReader od feedly client.

**Comment by Tunous** [comment]
With load next group you mean behavior like after pressing refresh?

**Comment by fi9o** [comment]
Yes, its thats what i want to Say. :)

**Comment by kontrastylez** [comment]
Other apps do this a little bit different.

For example, you have some groups/folders (games, it, news etc.), which are shown in navigation drawer. If you are reading articles by group, the app automatically switches to the next group, when all articles of an group are marked as read.

If you're reading by groups in SwipeNews, you have to manually switch to the next group via navigation drawer.

**Comment by Tunous** [comment]
@kontrastylez
That's pretty interesting. Do you know how these applications decide to which stream move next? 

___

The idea of refreshing content when marking all as read is something that I considered before but decided to analyze how the users use buttons in all read view before changing anything. What I am observing is that most users are marking content as read and then leave the app without checking if something new appeared. I'm not sure if it's good idea to make mark all as read auto refresh as it could be a bit confusing for the users if they see new content after using that action. Perhaps if I tried to add some sort of snackbar showing that there is new content it would work. It's kind of a hard decision... Definetly in my case I would prefer the mark all as read to auto refresh but I want SwipeNews to have most popular and not confusing defaults.

**Comment by Tunous** [comment]
Quick idea if I were to implement both of these features:

- When in main reading list mark all as read also refreshes to check for new content (and shows snackbar to display it, if something was found?)
- When in folder stream it moves to next folder
- When in subscription stream it moves to next subscription 
- When in tag stream it moves to next tag?

**Comment by kontrastylez** [comment]
@Tunous 
I think that they just open the next group with unread articles (that means the group, which is shown under the actual group in navigation drawer).

Your four options seem to be nice. But I personally would do automatic refresh a little bit different. I would prefer a setting to acitivate/deactivate (maybe deactivated per default?) automatic refresh, when all articles are marked as read. If the setting is activated, it would always directly refresh and show new articles, without showing a snackbar.

**Comment by Tunous** [comment]
Yes, your idea sounds like it would be best here. I'll probably go with that.

**Comment by Tunous** [comment]
Moved the idea for auto refresh to separate issue: #61.
