### ISSUE TITLE
Customizable article link sharing format

### ISSUE THREAD

**Issue by Tunous** [Tunous/SwipeNews-Issues#73]
> Can you add an option to share an article link, along with a small summary or first paragraph if its available? Like in the format,

```
[Link]

[Short Summary or first paragraph]
```

> Also, suppose I want to share an important paragraph from an article. So I long press on the article and select the text that I need and share it. Can an option be added to automatically append the article link along with it, if it's do-able? Like in the format,

```
[Selected text]

[Article link]
```

**Comment by Tunous** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Improved article link sharing](https://trello.com/c/Wr7NOXO0/962-improved-article-link-sharing)

**Comment by Tunous** [comment]
Implemented the first request in a format:

```
[Title]

[Summary] - [Link]
```

**Comment by Tunous** [comment]
Another option for the second request is to implement customizable share format like in this screenshot:

![screenshot_20170414-103822](https://cloud.githubusercontent.com/assets/5156340/25039687/37a73d02-2105-11e7-99ba-bf844d6b22c1.png)

**Comment by kontrastylez** [comment]
Would it be possible to integrate a separate option/function to really (only) share the article? The currently used format isn't really useful for me, because I would like to only share the link and not the complete (sometimes very, very long) article text.

**Comment by Tunous** [comment]
That probably should be a default option with an entry in settings screen to include summary when sharing.

**Comment by Tunous** [comment]
@kontrastylez The setting to enable sharing links together with summary has been added in **version 0.22.1** (to be released soon). By default, it is disabled which means that only the article link will be shared.

**Comment by Tunous** [comment]
I decided that further customization is not needed. Closing.
