### ISSUE TITLE
Customizable long-press menu for article list

### ISSUE THREAD

**Issue by kontrastylez** [Tunous/SwipeNews-Issues#74]
Is it possible to make the long-press menu in article list customizable? The only option in this menu, that i normally use, is "mark above as read". As this option is at the end of this menu, it would be nice to change the sorting to move it to the top of the list.

**Comment by Tunous** [comment]
I don't think that it's worth doing it. It would be useful only for a really small amount of users and there are more popular features to work on. 

The correct solution would be to reorder this list based on the popularity of the actions. Right now it's mostly ordered randomly as I was adding options and grouping them. 

So the question we have to ask is **what is the optimal sort order** . _Mark above as read_ action looks to be one of the most popular so it indeed should be located higher.

**Comment by Tunous** [comment]
1. mark above as read
2. share link
3. toggle read
4. toggle starred
5. read later

That's top 5 most used actions from here currently...

**Comment by kontrastylez** [comment]
That's a good solution. Your suggestion for sort order sounds perfect for me.

**Comment by Tunous** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Re-order items in article long-press menu](https://trello.com/c/GLAgBPZx/984-re-order-items-in-article-long-press-menu)

**Comment by Tunous** [comment]
Here is the order I'm going for:

![screenshot_1492007401](https://cloud.githubusercontent.com/assets/5156340/24963060/da151f1e-1f9d-11e7-937e-28e6e2781ee6.png)

Let me know if you think that something is bad.
