### ISSUE TITLE
New place to manage translations

### ISSUE THREAD

**Issue by Tunous** [Tunous/SwipeNews-Issues#76]
> Localize will shut down on October 31, 2018. Please export all your important data before that date.

**Comment by Tunous** [comment]
@kontrastylez You were very helpful with German so I'd like to hear your opinion about a new place to manage translations.

I've decided that it would be best to use Google Spreadsheets for that purpose. For that, I'm working on a small script which will help me with uploading and downloading of the translations.

Now [here](https://docs.google.com/spreadsheets/d/1tbOHHW6B6tlEZZ5FZfAr_Y5PMmNkKieykbMKb5vubr0/edit?usp=sharing) is an example spreadsheet. Could you take a look at this and tell me if there is anything that could be improved? For example, I'm interested in seeing which format is better: without wrapping or with wrapping like on rows 40-60 or even with clipping like on rows 70-90. But if there is anything else you could point out I would be really grateful.

Feel free to mess with the linked spreadsheet. I just created it for testing purposes for now.

I plan on switching to this after new version is released (which will be as soon as I finish my internal testing in few days)

**Comment by kontrastylez** [comment]
It isn't as userfriendly as "Localize", while I was normally doing the translations on smartphone or tablet. But I also see, that comparable services seem to be very expensive.

I have a few improvements, maybe they are feasible:

1. One table per language or even own spreadsheets per language
2. If you choose own spreadsheets per language, a small user management is doable. The sheet wouldn't have to be public, so that you can choose, who has access to the translation of an language.
3. Cells should be formatted to wrap the text
4. Mark empty cells (missing translations) with colored background via conditional formatting

I copied your table as new table "de". There, I did a few changes to the layout. That's how I would do it.


Maybe, only if you have an server for hosting, the following software could also be an option: https://weblate.org/

**Comment by Tunous** [comment]
> while I was normally doing the translations on smartphone or tablet

I find Android app for Google sheets comfortable. Did you try using it?

> One table per language

Yeah I've thought about this too but wasn't sure. I'll update my script to support this option. 

> If you choose own spreadsheets per language, a small user management is doable. The sheet wouldn't have to be public, so that you can choose, who has access to the translation of an language.

It's an interesting option but not what I'm aiming for. 

> 3. Cells should be formatted to wrap the text
> 4. Mark empty cells (missing translations) with colored background via conditional formatting

Will do.

> Maybe, only if you have an server for hosting, the following software could also be an option: https://weblate.org/

Unfortunately I do not own one and the app currently doesn't make much money to afford it just from its income. I wouldn't want to have to pay additionally.

___

I decided to try spreadsheets as they are a really powerful tool that provides some nice features out of box:

- Filtering so you can for example only see untranslated strings 
- Comments and notes for each cell allowing easy discussions 
- Notifications about changes 
- Changes history with reverting, marking interesting points in history (e.g. a release)
- Multi-user editing 
- Option to display automatic translations through Google Translate
- No need to create accounts to contribute 

Anyway, thank you for the feedback. I'll make mentioned changes and report back.

**Comment by Tunous** [comment]
BTW the script I'm creating will be open source for other developers to use in their own apps too. That's why I want this solution to be as perfect as possible :)

I could even in future add little companion app for translators. I see a potential here.

**Comment by kontrastylez** [comment]
I'm really fine with your decision.

I tested it on smartphone. That's why I proposed to choose one table/sheet per language. With all languages in one table, it was hard to overview. I think this will work very well with Google Spreadsheets.

I especially like the open source thing, because I guess, that it could help many "smaller" developers. :) And of course, you shouldn't pay additinally for that. Development itself is expensive enough.

I'm looking forward to testing the new translation tool. ;)

**Comment by Tunous** [comment]
[Here](https://docs.google.com/spreadsheets/d/1NhPlLS4LDCCyx-6tVOsoeftbk5AAL_E_V5W74AfjgS8/edit?usp=sharing) is another test spreadsheet with "multi-sheet" format. Wrapping appears to be not working correctly when set from the script but it's simple to set up that manually. (I'll do that for final version)
The first sheet could be used to give instructions about how the translating works and direct users to the sheets for the languages they want to translate. Do you have any suggestions for this?
The second sheet is provided so the users can easily duplicate it when adding new languages.

And that should be all. Everything is parsed and uploaded correctly, downloading works too so my script is ready for final work. Let me know if you have any more suggestions.

And [here](https://github.com/Tunous/StringSheet) is source code for the script.

**Comment by kontrastylez** [comment]
This looks very good.

I don't see an option to link to a special sheet. Do you know if this is possible in the web version of Google Spreadsheets? And do these links work within the android app? Then it would be nice, to have one link to each language sheet in the overview sheet.

**Comment by Tunous** [comment]
When you switch between sheets you can notice how the number at the end of the link in address bar changes. This number tells to which sheet to link directly.

I do not see a way to get these links from within the app but they do work here. If you follow that link and have sheets app installed it will automatically open the corresponding sheet.

That's for linking through links to outside of the spreadsheet. From inside of spreadsheet you can create a hyperlink using these links (`=HYPERLINK(link; name)`). I've added one now to see and it works both on mobile and the web version.

**Comment by kontrastylez** [comment]
This works perfectly.👍

**Comment by Tunous** [comment]
Great. I'll link to the final spreadsheet for SwipeNews once I fix few bugs and download current translations from old service.

**Comment by kontrastylez** [comment]
By the way, would it be possible, that you add more comments, what the descriptions should concretely mean? For example, the word "next" could be "nächste" or "nächstes" or "weiter" in german.

**Comment by Tunous** [comment]
Yes that's in my plans. The old service didn't parse them so I never bothered but now that's it available I'll add as many comments as possible.

**Comment by Tunous** [comment]
https://docs.google.com/spreadsheets/d/14x7VprNLmvh3OpAF3hnQSMLFlRtnn-1T-pewwVRBs1g/edit#gid=0 

That's a link to the final spreadsheet. You can now use it to translate.
