### ISSUE TITLE
Problem with Chrome Custom Tabs when going back

### ISSUE THREAD

**Issue by kontrastylez** [Tunous/SwipeNews-Issues#78]
Since last update, I have a problem with Chrome Custom Tabs, when I open an article in browser from article list (via swipe gesture or long press menu). When I press the back button one time, the start page of Chrome is shown, instead of going back to article list.

This problem doesn't occur, when I open an article in browser from article content screen.

**Comment by Tunous** [comment]
Hmm, probably something broke in the latest support library as that is the only thing I changed that could deal with it. 

Thanks for the report, I'll try to get it fixed in next bug fix release.

**Comment by Tunous** [comment]
Note for myself: http://stackoverflow.com/a/38224859/2630152. I actually changed the launch mode of primary screen to make it work with new navigation shortcut. Need to test the other option mentioned in link.

**Comment by kontrastylez** [comment]
It seems as if the problem had disappeared by itself. I can not reproduce the problem anymore.

**Comment by Tunous** [comment]
Yep, fixed for me too. I think they fixed this on Chrome's side as there was update to it today for me.
