### ISSUE TITLE
Auto refresh reading list

### ISSUE THREAD

**Issue by kontrastylez** [Tunous/SwipeNews-Issues#82]
I really like the setting "Automatically go to next stream after marking all articles as read". But sometimes I also use the main reading list instead of streams. Would it be possible, that this screen would automatically refresh, when all articles are marked as read?

That would be like a combination of the options "Automatically go to next stream after marking all articles as read" and "Refresh content when marking all as read".

**Comment by Tunous** [comment]
Yeah I thought about this too. I guess these settings shouldn't disable each other. I'll probably make it so if both of them are enabled then it'll refresh when in reading list or go to next stream when in other screens.

**Comment by Tunous** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Auto refresh reading list option when stream navigation is enabled](https://trello.com/c/Fzs4Z0Yu/987-auto-refresh-reading-list-option-when-stream-navigation-is-enabled)
