### ISSUE TITLE
Allow customizing double-tap gesture in article content

### ISSUE THREAD

**Issue by moben** [Tunous/SwipeNews-Issues#93]
I would love to be able to set double-tap to open in browser because on bigger screens that is easier to do than tapping the title at the top of the screen, but I assume all actions that are available for the Floating Action Button in the article content view would be appropriate.

Similar to #66 and that might be preferable because double tap can be problematic if there is a link or image in the way. I personally only need one of these, but I assume there are people who want 3 different actions easily accessible (FAB, FAB long-press, double-tap content).

**Comment by Tunous** [comment]
Sounds good. I'll probably add all of them (perhaps #24 too) as they are super easy to implement :)

Just need to group them nicely in Settings > Gestures section:

- Article
  - Click action
  - Long click action
  - Swipe left action
  - Swipe right action
- Floating Action Button - List screen
  - Click action
  - Long click action
- Floating Action Button - Content screen
  - Click action
  - Long click action
- Article content header
  - Click action
  - Long click action
- Other
  - Article content double tab action

This could probably work, but I'm not sure...

**Comment by Tunous** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [More customizable gestures](https://trello.com/c/gDSw89c1/1043-more-customizable-gestures)
